### ISSUE TITLE
Error on creating a new user account.

### ISSUE THREAD

**Issue by bjoern-st** [backdrop-contrib/trigger_actions#6]
Unfortunatly there is a problem with the trigger module.
When creating a new user account, the trigger module throws an error:
PHP Version is:  7.1.15

```
Warning: Parameter 1 to trigger_actions_user_insert() expected to be a reference, value given in module_invoke_all() (Zeile 947 von /html/core/includes/module.inc).
```

```
ArgumentCountError: Too few arguments to function trigger_actions_user_insert(), 1 passed in /html/core/includes/module.inc on line 947 and exactly 2 expected in trigger_actions_user_insert() (Zeile 588 von /html/modules/trigger_actions/trigger_actions.module).
```

If I can help in any way, please contact me.

**Comment by Graham-72** [comment]
@bjoern-st thanks for reporting this. I think this is now fixed.

**Comment by bjoern-st** [comment]
@Graham-72 
Yes - it is working now.
Thank you for fixing.

Are you going to create a new release? 

Cheers Bjoern

**Comment by Graham-72** [comment]
@bjoern-st thanks for confirming. Yes, I will make a new release but first I would like to check that no other fixes are needed at the moment.
